workflows:
  android-debug:
    name: Build Android DEBUG APK
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build DEBUG APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
